export const FETCH_PLACE_DETAILS_REQUEST = 'FETCH_PLACE_DETAILS_REQUEST';
export const FETCH_PLACE_DETAILS_SUCCESS = 'FETCH_PLACE_DETAILS_SUCCESS';
export const FETCH_PLACE_DETAILS_FAILED = 'FETCH_PLACE_DETAILS_FAILED';