export const FETCH_USER_ACTIVITIES_REQUEST = 'FETCH_USER_ACTIVITIES_REQUEST';
export const FETCH_USER_ACTIVITIES_SUCCESS = 'FETCH_USER_ACTIVITIES_SUCCESS';
export const FETCH_USER_ACTIVITIES_FAILED = 'FETCH_USER_ACTIVITIES_FAILED';
export const INSERT_USER_ACTIVITY_REQUEST = 'INSERT_USER_ACTIVITY_REQUEST';
export const INSERT_USER_ACTIVITY_SUCCESS = 'INSERT_USER_ACTIVITY_SUCCESS';
export const INSERT_USER_ACTIVITY_FAILED = 'INSERT_USER_ACTIVITY_FAILED';