import i18n from 'i18n-js';

export const weatherHandler = weatherId => {
    switch (weatherId) {
        case 200:
            return i18n.t('thunderstormWithLightRain');
        case 201:
            return i18n.t('thunderstormWithRain');
        case 202:
            return i18n.t('thunderstormWithHeavyRain');
        case 210:
            return i18n.t('lightThunderstorm');
        case 211:
            return i18n.t('thunderstorm');
        case 212:
            return i18n.t('heavyThunderstorm');
        case 221:
            return i18n.t('raggedThunderstorm');
        case 230:
            return i18n.t('thunderstormWithLightDrizzle');
        case 231:
            return i18n.t('thunderstormWithDrizzle');
        case 232:
            return i18n.t('thunderstormWithHeavyDrizzle');
        case 300:
            return i18n.t('lightIntensityDrizzle');
        case 301:
            return i18n.t('drizzle');
        case 302:
            return i18n.t('heavyIntensityDrizzle');
        case 310:
            return i18n.t('lightIntensityDrizzleRain');
        case 311:
            return i18n.t('drizzleRain');
        case 312:
            return i18n.t('heavyIntensityDrizzleRain');
        case 313:
            return i18n.t('showerRainAndDrizzle');
        case 314:
            return i18n.t('heavyShowerRainAndDrizzle');
        case 321:
            return i18n.t('showerDrizzle');
        case 500:
            return i18n.t('lightRain');
        case 501:
            return i18n.t('moderateRain');
        case 502:
            return i18n.t('heavyIntensityRain');
        case 503:
            return i18n.t('veryHeavyRain');
        case 504:
            return i18n.t('extremeRain');
        case 511:
            return i18n.t('freezingRain');
        case 520:
            return i18n.t('lightIntensityShowerRain');
        case 521:
            return i18n.t('showerRain');
        case 522:
            return i18n.t('heavyIntensityShowerRain');
        case 531:
            return i18n.t('raggedShowerRain');
        case 600:
            return i18n.t('lightSnow');
        case 601:
            return i18n.t('snow');
        case 602:
            return i18n.t('heavySnow');
        case 611:
            return i18n.t('sleet');
        case 612:
            return i18n.t('lightShowerSleet');
        case 613:
            return i18n.t('showerSleet');
        case 615:
            return i18n.t('lightRainAndSnow');
        case 616:
            return i18n.t('rainAndSnow');
        case 620:
            return i18n.t('lightShowerSnow');
        case 621:
            return i18n.t('showerSnow');
        case 622:
            return i18n.t('heavyShowerSnow');
        case 701:
            return i18n.t('mist');
        case 711:
            return i18n.t('smoke');
        case 721:
            return i18n.t('haze');
        case 731:
            return i18n.t('dustWhirls');
        case 741:
            return i18n.t('fog');
        case 751:
            return i18n.t('sand');
        case 761:
            return i18n.t('dust');
        case 762:
            return i18n.t('volcanicAsh');
        case 771:
            return i18n.t('squalls');
        case 781:
            return i18n.t('tornado');
        case 800:
            return i18n.t('clearSky');
        case 801:
            return i18n.t('fewClouds');
        case 802:
            return i18n.t('scatteredClouds');
        case 803:
            return i18n.t('brokenClouds');
        case 804:
            return i18n.t('overcastClouds');
    }
};